/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2-0-g3735e28

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: RoverMasterNode_30_V1.0.xdd
        File Version: 1

        Created:      9/25/2024 2:42:24 PM
        Created By:   
        Modified:     10/21/2024 3:46:53 PM
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: RoverMasterNode
        Product ID:   

        Description:  STM32
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 2
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
#define OD_CNT_ARR_1029 2
#define OD_CNT_ARR_2013 2
#define OD_CNT_ARR_2026 2
#define OD_CNT_ARR_6083 2
#define OD_CNT_ARR_6084 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    uint8_t x1029_errorBehaviorObject_sub0;
    uint8_t x1029_errorBehaviorObject[OD_CNT_ARR_1029];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOClient;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOClient;
    } x1281_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
    uint16_t x2008_turnOnSpeed;
    uint16_t x2009_registerConfiguration;
    uint16_t x200D_CANID;
    int16_t x200F_syncFlag;
    uint32_t x2015_maxCurrent;
    uint8_t x2026_temperature_sub0;
    uint16_t x2026_temperature[OD_CNT_ARR_2026];
    uint16_t x2027_motorStateRegister;
    uint16_t x2028_hallInputState;
    uint16_t x6040_controlWord;
    uint16_t x6041_stateWord;
    int8_t x6060_motionMode;
    uint32_t x6061_motionModeState;
    int32_t x606C_currentSpeedFeedBack;
    int16_t x6071_targetTorque;
    int16_t x6074_realTimeCommandTorque;
    int16_t x6077_realTimeTorqueFeedback;
    int32_t x607A_targetPosition;
    uint32_t x6081_maxSpeedPositionMode;
    uint32_t x6082_starStopSpeedPositionMode;
    uint8_t x6083_STypeAccelerationTime_sub0;
    uint32_t x6083_STypeAccelerationTime[OD_CNT_ARR_6083];
    uint8_t x6084_STypeDecelerationTime_sub0;
    uint32_t x6084_STypeDecelerationTime[OD_CNT_ARR_6084];
    uint32_t x6085_emergencyStopDecelerationTime;
    uint32_t x6087_torqueSlope;
    int32_t x60FF_targetSpeed;
    uint16_t x7040_controlWord;
    int32_t x706C_currentSpeedFeedBack;
    int32_t x70FF_targetSpeed;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint32_t x2005_clearFeedbackBit;
    uint32_t x2006_clearCurrentPositionBit;
    uint32_t x2007_limitedStopMethod;
    uint16_t x200A_maxSpeed;
    uint8_t x2013_temperatureThreshold_sub0;
    uint16_t x2013_temperatureThreshold[OD_CNT_ARR_2013];
    uint16_t x2014_ratedCurrent;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1002 &OD->list[2]
#define OD_ENTRY_H1003 &OD->list[3]
#define OD_ENTRY_H1005 &OD->list[4]
#define OD_ENTRY_H1006 &OD->list[5]
#define OD_ENTRY_H1007 &OD->list[6]
#define OD_ENTRY_H1008 &OD->list[7]
#define OD_ENTRY_H1009 &OD->list[8]
#define OD_ENTRY_H100A &OD->list[9]
#define OD_ENTRY_H100C &OD->list[10]
#define OD_ENTRY_H100D &OD->list[11]
#define OD_ENTRY_H1010 &OD->list[12]
#define OD_ENTRY_H1011 &OD->list[13]
#define OD_ENTRY_H1012 &OD->list[14]
#define OD_ENTRY_H1014 &OD->list[15]
#define OD_ENTRY_H1015 &OD->list[16]
#define OD_ENTRY_H1016 &OD->list[17]
#define OD_ENTRY_H1017 &OD->list[18]
#define OD_ENTRY_H1018 &OD->list[19]
#define OD_ENTRY_H1019 &OD->list[20]
#define OD_ENTRY_H1029 &OD->list[21]
#define OD_ENTRY_H1200 &OD->list[22]
#define OD_ENTRY_H1280 &OD->list[23]
#define OD_ENTRY_H1281 &OD->list[24]
#define OD_ENTRY_H1400 &OD->list[25]
#define OD_ENTRY_H1401 &OD->list[26]
#define OD_ENTRY_H1402 &OD->list[27]
#define OD_ENTRY_H1403 &OD->list[28]
#define OD_ENTRY_H1600 &OD->list[29]
#define OD_ENTRY_H1601 &OD->list[30]
#define OD_ENTRY_H1602 &OD->list[31]
#define OD_ENTRY_H1603 &OD->list[32]
#define OD_ENTRY_H1800 &OD->list[33]
#define OD_ENTRY_H1801 &OD->list[34]
#define OD_ENTRY_H1802 &OD->list[35]
#define OD_ENTRY_H1803 &OD->list[36]
#define OD_ENTRY_H1A00 &OD->list[37]
#define OD_ENTRY_H1A01 &OD->list[38]
#define OD_ENTRY_H1A02 &OD->list[39]
#define OD_ENTRY_H1A03 &OD->list[40]
#define OD_ENTRY_H2005 &OD->list[41]
#define OD_ENTRY_H2006 &OD->list[42]
#define OD_ENTRY_H2007 &OD->list[43]
#define OD_ENTRY_H2008 &OD->list[44]
#define OD_ENTRY_H2009 &OD->list[45]
#define OD_ENTRY_H200A &OD->list[46]
#define OD_ENTRY_H200D &OD->list[47]
#define OD_ENTRY_H200F &OD->list[48]
#define OD_ENTRY_H2013 &OD->list[49]
#define OD_ENTRY_H2014 &OD->list[50]
#define OD_ENTRY_H2015 &OD->list[51]
#define OD_ENTRY_H2026 &OD->list[52]
#define OD_ENTRY_H2027 &OD->list[53]
#define OD_ENTRY_H2028 &OD->list[54]
#define OD_ENTRY_H6040 &OD->list[55]
#define OD_ENTRY_H6041 &OD->list[56]
#define OD_ENTRY_H6060 &OD->list[57]
#define OD_ENTRY_H6061 &OD->list[58]
#define OD_ENTRY_H606C &OD->list[59]
#define OD_ENTRY_H6071 &OD->list[60]
#define OD_ENTRY_H6074 &OD->list[61]
#define OD_ENTRY_H6077 &OD->list[62]
#define OD_ENTRY_H607A &OD->list[63]
#define OD_ENTRY_H6081 &OD->list[64]
#define OD_ENTRY_H6082 &OD->list[65]
#define OD_ENTRY_H6083 &OD->list[66]
#define OD_ENTRY_H6084 &OD->list[67]
#define OD_ENTRY_H6085 &OD->list[68]
#define OD_ENTRY_H6087 &OD->list[69]
#define OD_ENTRY_H60FF &OD->list[70]
#define OD_ENTRY_H7040 &OD->list[71]
#define OD_ENTRY_H706C &OD->list[72]
#define OD_ENTRY_H70FF &OD->list[73]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1002_manufacturerStatusRegister &OD->list[2]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[3]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[4]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[5]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[6]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[7]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[8]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[9]
#define OD_ENTRY_H100C_guardTime &OD->list[10]
#define OD_ENTRY_H100D_lifeTimeFactor &OD->list[11]
#define OD_ENTRY_H1010_storeParameters &OD->list[12]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[13]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[14]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[15]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[16]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[17]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[18]
#define OD_ENTRY_H1018_identity &OD->list[19]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[20]
#define OD_ENTRY_H1029_errorBehaviorObject &OD->list[21]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[22]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[23]
#define OD_ENTRY_H1281_SDOClientParameter &OD->list[24]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[33]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[34]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[35]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[36]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[37]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[38]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[39]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[40]
#define OD_ENTRY_H2005_clearFeedbackBit &OD->list[41]
#define OD_ENTRY_H2006_clearCurrentPositionBit &OD->list[42]
#define OD_ENTRY_H2007_limitedStopMethod &OD->list[43]
#define OD_ENTRY_H2008_turnOnSpeed &OD->list[44]
#define OD_ENTRY_H2009_registerConfiguration &OD->list[45]
#define OD_ENTRY_H200A_maxSpeed &OD->list[46]
#define OD_ENTRY_H200D_CANID &OD->list[47]
#define OD_ENTRY_H200F_syncFlag &OD->list[48]
#define OD_ENTRY_H2013_temperatureThreshold &OD->list[49]
#define OD_ENTRY_H2014_ratedCurrent &OD->list[50]
#define OD_ENTRY_H2015_maxCurrent &OD->list[51]
#define OD_ENTRY_H2026_temperature &OD->list[52]
#define OD_ENTRY_H2027_motorStateRegister &OD->list[53]
#define OD_ENTRY_H2028_hallInputState &OD->list[54]
#define OD_ENTRY_H6040_controlWord &OD->list[55]
#define OD_ENTRY_H6041_stateWord &OD->list[56]
#define OD_ENTRY_H6060_motionMode &OD->list[57]
#define OD_ENTRY_H6061_motionModeState &OD->list[58]
#define OD_ENTRY_H606C_currentSpeedFeedBack &OD->list[59]
#define OD_ENTRY_H6071_targetTorque &OD->list[60]
#define OD_ENTRY_H6074_realTimeCommandTorque &OD->list[61]
#define OD_ENTRY_H6077_realTimeTorqueFeedback &OD->list[62]
#define OD_ENTRY_H607A_targetPosition &OD->list[63]
#define OD_ENTRY_H6081_maxSpeedPositionMode &OD->list[64]
#define OD_ENTRY_H6082_starStopSpeedPositionMode &OD->list[65]
#define OD_ENTRY_H6083_STypeAccelerationTime &OD->list[66]
#define OD_ENTRY_H6084_STypeDecelerationTime &OD->list[67]
#define OD_ENTRY_H6085_emergencyStopDecelerationTime &OD->list[68]
#define OD_ENTRY_H6087_torqueSlope &OD->list[69]
#define OD_ENTRY_H60FF_targetSpeed &OD->list[70]
#define OD_ENTRY_H7040_controlWord &OD->list[71]
#define OD_ENTRY_H706C_currentSpeedFeedBack &OD->list[72]
#define OD_ENTRY_H70FF_targetSpeed &OD->list[73]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
