/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2-0-g3735e28

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD_ZLAC8030L.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ZLAC8030L_ATTR_PERSIST_COMM OD_ZLAC8030L_PERSIST_COMM_t OD_ZLAC8030L_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x100C_guardTime = 0x0000,
    .x100D_lifeTimeFactor = 0x00,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0xEA60,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000100,
        .productCode = 0x00000001,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1029_errorBehaviorObject_sub0 = 0x02,
    .x1029_errorBehaviorObject = {0x00, 0x00},
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x00000600,
        .COB_IDServerToClientRx = 0x00000580,
        .node_IDOfTheSDOClient = 0x01
    },
    .x1281_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x00000600,
        .COB_IDServerToClientRx = 0x00000580,
        .node_IDOfTheSDOClient = 0x02
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000281,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000282,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x606C0020,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x706C0020,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000301,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000302,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000201,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000202,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x60FF0020,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x70FF0020,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x60400010,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x70400010,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x2008_turnOnSpeed = 0x0000,
    .x2009_registerConfiguration = 0x0000,
    .x200D_CANID = 0x0000,
    .x200F_syncFlag = 0,
    .x2015_maxCurrent = 0x0000012C,
    .x2026_temperature_sub0 = 0x02,
    .x2026_temperature = {0x0000, 0x0000},
    .x2027_motorStateRegister = 0x0000,
    .x2028_hallInputState = 0x0000,
    .x6040_controlWord = 0x0000,
    .x6041_stateWord = 0x0000,
    .x6060_motionMode = 0,
    .x6061_motionModeState = 0x00000000,
    .x606C_currentSpeedFeedBack = 0,
    .x6071_targetTorque = 0,
    .x6074_realTimeCommandTorque = 0,
    .x6077_realTimeTorqueFeedback = 0,
    .x607A_targetPosition = 0,
    .x6081_maxSpeedPositionMode = 0x00000000,
    .x6082_starStopSpeedPositionMode = 0x00000000,
    .x6083_STypeAccelerationTime_sub0 = 0x02,
    .x6083_STypeAccelerationTime = {0x000001F4, 0x000001F4},
    .x6084_STypeDecelerationTime_sub0 = 0x02,
    .x6084_STypeDecelerationTime = {0x000001F4, 0x000001F4},
    .x6085_emergencyStopDecelerationTime = 0x0000000A,
    .x6087_torqueSlope = 0x0000012C,
    .x60FF_targetSpeed = 0,
    .x7040_controlWord = 0x0000,
    .x706C_currentSpeedFeedBack = 0,
    .x70FF_targetSpeed = 0
};

OD_ZLAC8030L_ATTR_RAM OD_ZLAC8030L_RAM_t OD_ZLAC8030L_RAM = {
    .x1001_errorRegister = 0x00,
    .x1002_manufacturerStatusRegister = 0x00000000,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2005_clearFeedbackBit = 0x00000000,
    .x2006_clearCurrentPositionBit = 0x00000000,
    .x2007_limitedStopMethod = 0x00000000,
    .x200A_maxSpeed = 0x0000,
    .x2013_temperatureThreshold_sub0 = 0x02,
    .x2013_temperatureThreshold = {0x0320, 0x0320},
    .x2014_ratedCurrent = 0x0096
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1002_manufacturerStatusRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_100C_guardTime;
    OD_obj_var_t o_100D_lifeTimeFactor;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_array_t o_1029_errorBehaviorObject;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1281_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_var_t o_2005_clearFeedbackBit;
    OD_obj_var_t o_2006_clearCurrentPositionBit;
    OD_obj_var_t o_2007_limitedStopMethod;
    OD_obj_var_t o_2008_turnOnSpeed;
    OD_obj_var_t o_2009_registerConfiguration;
    OD_obj_var_t o_200A_maxSpeed;
    OD_obj_var_t o_200D_CANID;
    OD_obj_var_t o_200F_syncFlag;
    OD_obj_array_t o_2013_temperatureThreshold;
    OD_obj_var_t o_2014_ratedCurrent;
    OD_obj_var_t o_2015_maxCurrent;
    OD_obj_array_t o_2026_temperature;
    OD_obj_var_t o_2027_motorStateRegister;
    OD_obj_var_t o_2028_hallInputState;
    OD_obj_var_t o_6040_controlWord;
    OD_obj_var_t o_6041_stateWord;
    OD_obj_var_t o_6060_motionMode;
    OD_obj_var_t o_6061_motionModeState;
    OD_obj_var_t o_606C_currentSpeedFeedBack;
    OD_obj_var_t o_6071_targetTorque;
    OD_obj_var_t o_6074_realTimeCommandTorque;
    OD_obj_var_t o_6077_realTimeTorqueFeedback;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_var_t o_6081_maxSpeedPositionMode;
    OD_obj_var_t o_6082_starStopSpeedPositionMode;
    OD_obj_array_t o_6083_STypeAccelerationTime;
    OD_obj_array_t o_6084_STypeDecelerationTime;
    OD_obj_var_t o_6085_emergencyStopDecelerationTime;
    OD_obj_var_t o_6087_torqueSlope;
    OD_obj_var_t o_60FF_targetSpeed;
    OD_obj_var_t o_7040_controlWord;
    OD_obj_var_t o_706C_currentSpeedFeedBack;
    OD_obj_var_t o_70FF_targetSpeed;
} OD_ZLAC8030LObjs_t;

static CO_PROGMEM OD_ZLAC8030LObjs_t OD_ZLAC8030LObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_ZLAC8030L_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1002_manufacturerStatusRegister = {
        .dataOrig = &OD_ZLAC8030L_RAM.x1002_manufacturerStatusRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100C_guardTime = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x100C_guardTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_100D_lifeTimeFactor = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x100D_lifeTimeFactor,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_ZLAC8030L_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_ZLAC8030L_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_ZLAC8030L_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_ZLAC8030L_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_ZLAC8030L_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1029_errorBehaviorObject = {
        .dataOrig0 = &OD_ZLAC8030L_PERSIST_COMM.x1029_errorBehaviorObject_sub0,
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1029_errorBehaviorObject[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOClient,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1281_SDOClientParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1281_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1281_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1281_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1281_SDOClientParameter.node_IDOfTheSDOClient,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2005_clearFeedbackBit = {
        .dataOrig = &OD_ZLAC8030L_RAM.x2005_clearFeedbackBit,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2006_clearCurrentPositionBit = {
        .dataOrig = &OD_ZLAC8030L_RAM.x2006_clearCurrentPositionBit,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2007_limitedStopMethod = {
        .dataOrig = &OD_ZLAC8030L_RAM.x2007_limitedStopMethod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2008_turnOnSpeed = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2008_turnOnSpeed,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_2009_registerConfiguration = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2009_registerConfiguration,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_200A_maxSpeed = {
        .dataOrig = &OD_ZLAC8030L_RAM.x200A_maxSpeed,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_200D_CANID = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x200D_CANID,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_200F_syncFlag = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x200F_syncFlag,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2013_temperatureThreshold = {
        .dataOrig0 = &OD_ZLAC8030L_RAM.x2013_temperatureThreshold_sub0,
        .dataOrig = &OD_ZLAC8030L_RAM.x2013_temperatureThreshold[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_2014_ratedCurrent = {
        .dataOrig = &OD_ZLAC8030L_RAM.x2014_ratedCurrent,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2015_maxCurrent = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2015_maxCurrent,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2026_temperature = {
        .dataOrig0 = &OD_ZLAC8030L_PERSIST_COMM.x2026_temperature_sub0,
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2026_temperature[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_2027_motorStateRegister = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2027_motorStateRegister,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2028_hallInputState = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x2028_hallInputState,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6040_controlWord = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6040_controlWord,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_stateWord = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6041_stateWord,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_motionMode = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6060_motionMode,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6061_motionModeState = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6061_motionModeState,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_currentSpeedFeedBack = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x606C_currentSpeedFeedBack,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6071_targetTorque = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6071_targetTorque,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6074_realTimeCommandTorque = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6074_realTimeCommandTorque,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6077_realTimeTorqueFeedback = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6077_realTimeTorqueFeedback,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_607A_targetPosition = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x607A_targetPosition,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6081_maxSpeedPositionMode = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6081_maxSpeedPositionMode,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6082_starStopSpeedPositionMode = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6082_starStopSpeedPositionMode,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_STypeAccelerationTime = {
        .dataOrig0 = &OD_ZLAC8030L_PERSIST_COMM.x6083_STypeAccelerationTime_sub0,
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6083_STypeAccelerationTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6084_STypeDecelerationTime = {
        .dataOrig0 = &OD_ZLAC8030L_PERSIST_COMM.x6084_STypeDecelerationTime_sub0,
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6084_STypeDecelerationTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6085_emergencyStopDecelerationTime = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6085_emergencyStopDecelerationTime,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6087_torqueSlope = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x6087_torqueSlope,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FF_targetSpeed = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x60FF_targetSpeed,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_7040_controlWord = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x7040_controlWord,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_706C_currentSpeedFeedBack = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x706C_currentSpeedFeedBack,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_70FF_targetSpeed = {
        .dataOrig = &OD_ZLAC8030L_PERSIST_COMM.x70FF_targetSpeed,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ZLAC8030L_ATTR_OD OD_entry_t OD_ZLAC8030LList[] = {
    {0x1000, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1001_errorRegister, NULL},
    {0x1002, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1002_manufacturerStatusRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &OD_ZLAC8030LObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x100C, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_100C_guardTime, NULL},
    {0x100D, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_100D_lifeTimeFactor, NULL},
    {0x1010, 0x05, ODT_ARR, &OD_ZLAC8030LObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &OD_ZLAC8030LObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &OD_ZLAC8030LObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &OD_ZLAC8030LObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1029, 0x03, ODT_ARR, &OD_ZLAC8030LObjs.o_1029_errorBehaviorObject, NULL},
    {0x1200, 0x03, ODT_REC, &OD_ZLAC8030LObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1280_SDOClientParameter, NULL},
    {0x1281, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1281_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &OD_ZLAC8030LObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &OD_ZLAC8030LObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &OD_ZLAC8030LObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &OD_ZLAC8030LObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &OD_ZLAC8030LObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &OD_ZLAC8030LObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x2005, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2005_clearFeedbackBit, NULL},
    {0x2006, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2006_clearCurrentPositionBit, NULL},
    {0x2007, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2007_limitedStopMethod, NULL},
    {0x2008, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2008_turnOnSpeed, NULL},
    {0x2009, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2009_registerConfiguration, NULL},
    {0x200A, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_200A_maxSpeed, NULL},
    {0x200D, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_200D_CANID, NULL},
    {0x200F, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_200F_syncFlag, NULL},
    {0x2013, 0x03, ODT_ARR, &OD_ZLAC8030LObjs.o_2013_temperatureThreshold, NULL},
    {0x2014, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2014_ratedCurrent, NULL},
    {0x2015, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2015_maxCurrent, NULL},
    {0x2026, 0x03, ODT_ARR, &OD_ZLAC8030LObjs.o_2026_temperature, NULL},
    {0x2027, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2027_motorStateRegister, NULL},
    {0x2028, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_2028_hallInputState, NULL},
    {0x6040, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6040_controlWord, NULL},
    {0x6041, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6041_stateWord, NULL},
    {0x6060, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6060_motionMode, NULL},
    {0x6061, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6061_motionModeState, NULL},
    {0x606C, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_606C_currentSpeedFeedBack, NULL},
    {0x6071, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6071_targetTorque, NULL},
    {0x6074, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6074_realTimeCommandTorque, NULL},
    {0x6077, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6077_realTimeTorqueFeedback, NULL},
    {0x607A, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_607A_targetPosition, NULL},
    {0x6081, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6081_maxSpeedPositionMode, NULL},
    {0x6082, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6082_starStopSpeedPositionMode, NULL},
    {0x6083, 0x03, ODT_ARR, &OD_ZLAC8030LObjs.o_6083_STypeAccelerationTime, NULL},
    {0x6084, 0x03, ODT_ARR, &OD_ZLAC8030LObjs.o_6084_STypeDecelerationTime, NULL},
    {0x6085, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6085_emergencyStopDecelerationTime, NULL},
    {0x6087, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_6087_torqueSlope, NULL},
    {0x60FF, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_60FF_targetSpeed, NULL},
    {0x7040, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_7040_controlWord, NULL},
    {0x706C, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_706C_currentSpeedFeedBack, NULL},
    {0x70FF, 0x01, ODT_VAR, &OD_ZLAC8030LObjs.o_70FF_targetSpeed, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD_ZLAC8030L = {
    (sizeof(OD_ZLAC8030LList) / sizeof(OD_ZLAC8030LList[0])) - 1,
    &OD_ZLAC8030LList[0]
};

OD_t *OD_ZLAC8030L = &_OD_ZLAC8030L;
